# Generated by Django 3.1.7 on 2022-05-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220518_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='', verbose_name='¿Area Privada?'),
        ),
    ]
